owner: hflabs
repo: dadata-uptime

sites:
    - name: Сайт
      url: https://dadata.ru/about/
      expectedStatusCodes: [200]
      maxResponseTime: 3000
    - name: Стандартизация
      url: https://cleaner.dadata.ru/actuator/health
      expectedStatusCodes: [200]
      maxResponseTime: 3000
    - name: Подсказки
      url: https://suggestions.dadata.ru/suggestions/api/4_1/rs/status
      expectedStatusCodes: [200]
      maxResponseTime: 3000

status-website:
    cname: status.dadata.ru
    logoUrl: https://raw.githubusercontent.com/hflabs/dadata-uptime/master/assets/logo.svg
    name: Статус DaData
    introTitle: «Дадата» помогает бизнесу наводить порядок в базах контактных данных.
    introMessage: Эта страница показывает статус доступности сервисов «Дадаты». Подробности — в [**телеграме**](https://t.me/dadataru_health).
    navbar:
        - title: Статус
          href: /
        - title: Телеграм
          href: https://t.me/dadataru_health
